### PR TITLE
Also accept uids to the -u argument

### PR DESCRIPTION
**Pull request by lamby**

### CODE REVIEW

**Comment by jonasdn** [comment]
Thanks!

I am not sure about this. What is the use-case? When do you have access to uid but not username?

**Comment by lamby** [comment]
> When do you have access to uid but not username?

I do a bunch of package builds in environments with deliberately "weird" stuff in order to try and break it (eg. extreme timezones, in the future, bizarre locales, dodgy getpwuid kinda stuff).

uid is also more reliable across dodgy filesystems such as NFS.. :)

.. but orthogonal to that, it seems to be a _de facto_ idiom in UNIX configuration files to accept both uids and usernames.

**Comment by jonasdn** [comment]
Do you have an example? Looking at strace or ltrace that both have an username argument I do not see them taking uid.

**Comment by lamby** [comment]
strace is hardly a good example of a unix tool!  (seen the code itself?)

**Comment by lamby** [comment]
Gentle ping on this? :)

**Comment by jonasdn** [comment]
Thank you!

**Pull request merged**
